schema:
    description: Creates Search Nodes for the specified cluster.
    attributes:
        - string: {}
          description: Label that identifies the cluster to create Search Nodes for.
          computed_optional_required: required
          tf_schema_name: cluster_name
          tf_model_name: ClusterName
          api_name: clusterName
          req_body_usage: omit_always
          sensitive: false
          create_only: true
          present_in_response: false
          required_on_create_input_only: false
        - string: {}
          description: Cloud service provider that manages your customer keys to provide an additional layer of Encryption At Rest for the cluster.
          computed_optional_required: computed
          tf_schema_name: encryption_at_rest_provider
          tf_model_name: EncryptionAtRestProvider
          api_name: encryptionAtRestProvider
          req_body_usage: omit_always
          sensitive: false
          create_only: false
          present_in_response: false
          required_on_create_input_only: false
        - string: {}
          description: |-
            Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

            **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.
          computed_optional_required: required
          tf_schema_name: group_id
          tf_model_name: GroupId
          api_name: groupId
          req_body_usage: omit_always
          sensitive: false
          create_only: true
          present_in_response: false
          required_on_create_input_only: false
        - string: {}
          description: Unique 24-hexadecimal digit string that identifies the search deployment.
          computed_optional_required: computed
          tf_schema_name: id
          tf_model_name: Id
          api_name: id
          req_body_usage: omit_always
          sensitive: false
          create_only: false
          present_in_response: false
          required_on_create_input_only: false
        - list_nested:
            nested_object:
                attributes:
                    - string: {}
                      description: Hardware specification for the Search Node instance sizes.
                      computed_optional_required: required
                      tf_schema_name: instance_size
                      tf_model_name: InstanceSize
                      api_name: instanceSize
                      req_body_usage: all_request_bodies
                      sensitive: false
                      create_only: false
                      present_in_response: false
                      required_on_create_input_only: false
                    - int64: {}
                      description: Number of Search Nodes in the cluster.
                      computed_optional_required: required
                      tf_schema_name: node_count
                      tf_model_name: NodeCount
                      api_name: nodeCount
                      req_body_usage: all_request_bodies
                      sensitive: false
                      create_only: false
                      present_in_response: false
                      required_on_create_input_only: false
          description: |-
            List of settings that configure the Search Nodes for your cluster.

            **NOTE**: We accept a single configuration for all nodes currently.
          custom_type:
            package: customtypes
            model: customtypes.NestedListValue[TFSpecsModel]
            schema: customtypes.NewNestedListType[TFSpecsModel](ctx)
          computed_optional_required: required
          tf_schema_name: specs
          tf_model_name: Specs
          api_name: specs
          req_body_usage: all_request_bodies
          sensitive: false
          create_only: false
          present_in_response: false
          required_on_create_input_only: false
        - string: {}
          description: Human-readable label that indicates the current operating condition of this search deployment.
          computed_optional_required: computed
          tf_schema_name: state_name
          tf_model_name: StateName
          api_name: stateName
          req_body_usage: omit_always
          sensitive: false
          create_only: false
          present_in_response: false
          required_on_create_input_only: false
        - bool:
            default: true
          description: Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to `true` and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to `false`, the timeout will not trigger resource deletion. If you suspect a transient error when the value is `true`, wait before retrying to allow resource deletion to finish. Default is `true`.
          computed_optional_required: computed_optional
          tf_schema_name: delete_on_create_timeout
          tf_model_name: DeleteOnCreateTimeout
          req_body_usage: omit_always
          sensitive: false
          create_only: true
          present_in_response: false
          required_on_create_input_only: false
        - timeouts:
            configurable_timeouts:
                - create
                - update
                - delete
          computed_optional_required: ""
          tf_schema_name: timeouts
          tf_model_name: Timeouts
          req_body_usage: omit_always
          sensitive: false
          create_only: false
          present_in_response: false
          required_on_create_input_only: false
operations:
    delete:
        wait:
            state_property: stateName
            pending_states:
                - IDLE
                - UPDATING
                - PAUSED
            target_states:
                - DELETED
            timeout_seconds: 10800
            min_timeout_seconds: 30
            delay_seconds: 60
        http_method: DELETE
        path: /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/search/deployment
    create:
        wait:
            state_property: stateName
            pending_states:
                - UPDATING
                - PAUSED
            target_states:
                - IDLE
            timeout_seconds: 10800
            min_timeout_seconds: 60
            delay_seconds: 60
        http_method: POST
        path: /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/search/deployment
    read:
        http_method: GET
        path: /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/search/deployment
    update:
        wait:
            state_property: stateName
            pending_states:
                - UPDATING
                - PAUSED
            target_states:
                - IDLE
            timeout_seconds: 10800
            min_timeout_seconds: 60
            delay_seconds: 60
        http_method: PATCH
        path: /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/search/deployment
    version_header: application/vnd.atlas.2025-03-12+json
name: search_deployment_api
packageName: searchdeploymentapi
