blank_issues_enabled: true
contact_links:
  - name: Terraform MongoDB Atlas Provider Feature Request
    url: https://feedback.mongodb.com/ideas?category=7548141186718564699
    about: Request a feature or up-vote an existing suggestion!
  - name: MongoDB Atlas Support
    url: https://support.mongodb.com/
    about: Support is provided under MongoDB Atlas support plans. Please submit support questions within the Atlas UI.
  - name: MongoDB Atlas 
    url: https://www.mongodb.com/cloud/atlas
    about: Learn more about MongoDB Atlas
