name: Slack Notification

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  precheck:
    if: ${{ github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'skip-slack-notification') }}
    runs-on: ubuntu-latest
    outputs:
      docfiles: ${{ steps.changes.outputs.docfiles }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          filters: |
            docfiles:
              - '.changelog/**'
              - 'website/**'
        
  notify-doc:
    needs: precheck
    if: ${{ needs.precheck.outputs.docfiles == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "hey ${{ secrets.SLACK_DOCS_TAG }}, this is APIx bot, can you please review <${{ github.event.pull_request.html_url }}|PR ${{ github.event.pull_request.number }}>? thanks a lot!"
                  }
                }
              ]
            }
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: pr-slack-docs
          append: true
          message: "APIx bot: message sent to Docs team"

  notify-apix:
    needs: precheck
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}> has ready for review <${{ github.event.pull_request.html_url }}|TF PR ${{ github.event.pull_request.number }}>"
                }
              ]
            }
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: pr-slack-apix
          append: true
          message: "APIx bot: message sent to APIx team"
